name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # メインブランチを指定（gh-pagesの場合は変更）
  workflow_dispatch:  # 手動実行も可能

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: GitHub Pages の設定
        uses: actions/configure-pages@v4

      - name: 必要なディレクトリを作成
        run: |
          mkdir -p public
          cp -r * public/
          
      - name: アーティファクトをアップロード
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: GitHub Pages にデプロイ
        id: deployment
        uses: actions/deploy-pages@v4
